// src/main/java/com/example/gardenchat/model/User.java
package com.example.gardenchat.model;

import lombok.Data; // Lombok annotation to generate boilerplate code like getters, setters, and more
import org.springframework.data.annotation.Id; // Annotation to mark the primary key field
import org.springframework.data.mongodb.core.mapping.Document; // Annotation to map this class to a MongoDB collection

// Lombok's @Data generates getters, setters, toString, equals, and hashCode methods automatically
@Data
// Maps this class to a MongoDB collection named "users"
@Document(collection = "users")
public class User {

    // Marks this field as the primary key in the MongoDB collection
    @Id
    private String id; // Unique identifier for each user (auto-generated by MongoDB)

    // Field for the username of the user
    private String username; // Unique username for the user

    // Field for the user's password
    private String password; // Password for the user's account

    // Field for the profile icon URL or path
    //private String profileIcon; // URL or path to the user's profile icon image
}
